### ISSUE TITLE
error getting credentials

### ISSUE THREAD

**Issue by melidosian** [OxNinja/SQLi-lab#1]
I am running into errors getting this running. I am trying to build this on an M1 MacBook Air. When I execute build.sh, I get the following output:

SQLi-lab git:(master) ./build.sh                                   
Password: **********
2023/06/08 12:09:09 must use ASL logging (which requires CGO) if running as root
[+] Running 0/0
 ⠋ db Pulling                                                              0.0s 
error getting credentials - err: exit status 1, out: ``

Please help me get this running, thank you :)

**Comment by OxNinja** [comment]
Hello, from google I get https://github.com/docker/compose/issues/9560#issuecomment-1370219176 maybe it can help you?
